### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by abdulrahman1s** [c8h10n4o2-tools/carpenter#2]
Please make some guards/escaping to avoid SQL Injection such as

```ts
// Unknown client-side data
const id = '1 OR 1 = 1'

const sql = $
    .from('table1')
    .where(`id = ${id}`)
    .select('*')
    .toString();
 
console.log(sql); // "SELECT * FROM table1 WHERE id = 1 OR 1 = 1"
```

**Comment by kemicofa** [comment]
@TheMaestro1s thanks for raising the issue and I must have missed the notification. In any case, the goal of this library is to help write SQL queries and not insert data like so.

You should instead do:
```javascript
const sql = $
    .from('table1')
    .where(`id = @id`)
    .select('*')
    .toString();
```

And then use your database library to safely inject your data.

For example, if you use the Spanner library from google, it already has such a feature. However, if this is really an issue I can look into it.
